import { useState, type FormEvent } from "react";
import { DatabaseIcon, PlusIcon, RefreshCwIcon, SettingsIcon } from "lucide-react";
import { api } from "../api";
import { SignOutButton, type DashboardData, type Mutate } from "../App";
import type { CatalogSource } from "../types";
import type { Language } from "../translations";
import { PageHeading, StateBadge, copy, formatDate } from "./shared";
import { Button } from "@/components/ui/button";
import { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Spinner } from "@/components/ui/spinner";
import { Textarea } from "@/components/ui/textarea";

export function SettingsView({ data, language, mutate, onLogout }: { data: DashboardData; language: Language; mutate: Mutate; onLogout: () => Promise<void> }) {
  const [adding, setAdding] = useState(false);
  return <section className="flex flex-col gap-7"><PageHeading title={copy(language, "设置", "Settings")} description={copy(language, "管理 Center、应用目录和登录会话。网络集成位于“网络”页面。", "Manage Center, app catalogs, and your session. Network integrations live on the Network page.")} action={<SignOutButton language={language} onLogout={onLogout} />} /><Card><CardHeader><CardTitle className="flex items-center gap-2"><SettingsIcon />Center</CardTitle><CardDescription>{copy(language, "当前运行信息", "Current runtime information")}</CardDescription><CardAction><StateBadge value="connected" /></CardAction></CardHeader><CardContent><dl className="grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-muted-foreground">{copy(language, "版本", "Version")}</dt><dd className="mt-1 font-medium">{data.status.version}</dd></div><div><dt className="text-muted-foreground">{copy(language, "节点", "Nodes")}</dt><dd className="mt-1 font-medium">{data.status.agents}</dd></div><div><dt className="text-muted-foreground">{copy(language, "应用", "Apps")}</dt><dd className="mt-1 font-medium">{data.applications.length}</dd></div></dl></CardContent></Card><div className="flex flex-col gap-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{copy(language, "应用目录", "App catalogs")}</h2><p className="mt-1 text-sm text-muted-foreground">{copy(language, "只从已验证签名的目录安装应用。", "Apps are installed only from verified signed catalogs.")}</p></div><Button onClick={() => setAdding(true)} size="sm"><PlusIcon data-icon="inline-start" />{copy(language, "添加目录", "Add catalog")}</Button></div><div className="grid gap-4 lg:grid-cols-2">{data.sources.map((source) => <SourceCard key={source.id} language={language} mutate={mutate} source={source} />)}</div></div><SourceSheet language={language} onClose={() => setAdding(false)} onSubmit={async (source) => { await mutate(() => api.createSource(source), copy(language, "应用目录已添加。", "App catalog added.")); setAdding(false); }} open={adding} /></section>;
}

function SourceCard({ language, mutate, source }: { language: Language; mutate: Mutate; source: CatalogSource }) {
  const [busy, setBusy] = useState(false);
  const refresh = async () => { setBusy(true); try { await mutate(() => api.refreshSource(source.id), copy(language, "目录已刷新。", "Catalog refreshed.")); } finally { setBusy(false); } };
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><DatabaseIcon />{source.displayName}</CardTitle><CardDescription className="truncate">{source.url}</CardDescription><CardAction><StateBadge value={source.lastError ? "failed" : source.enabled ? "active" : "disabled"} /></CardAction></CardHeader><CardContent><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">{copy(language, "上次同步", "Last sync")}</dt><dd className="mt-1">{formatDate(language, source.fetchedAt)}</dd></div><div><dt className="text-muted-foreground">{copy(language, "刷新间隔", "Refresh interval")}</dt><dd className="mt-1">{Math.round(source.refreshIntervalSeconds / 60)} min</dd></div></dl>{source.lastError ? <p className="mt-3 text-sm text-destructive">{source.lastError}</p> : null}</CardContent><CardFooter className="justify-end"><Button disabled={busy} onClick={() => void refresh()} size="sm" variant="outline">{busy ? <Spinner data-icon="inline-start" /> : <RefreshCwIcon data-icon="inline-start" />}{copy(language, "刷新", "Refresh")}</Button></CardFooter></Card>;
}

type SourceInput = { id: string; displayName: string; url: string; publicKey: string; bearerToken: string; customCA: string; refreshIntervalSeconds: number };

function SourceSheet({ language, onClose, onSubmit, open }: { language: Language; onClose: () => void; onSubmit: (source: SourceInput) => Promise<void>; open: boolean }) {
  const [source, setSource] = useState<SourceInput>({ id: "", displayName: "", url: "", publicKey: "", bearerToken: "", customCA: "", refreshIntervalSeconds: 3600 });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); try { await onSubmit(source); setSource({ id: "", displayName: "", url: "", publicKey: "", bearerToken: "", customCA: "", refreshIntervalSeconds: 3600 }); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Request failed"); } finally { setBusy(false); } };
  return <Sheet onOpenChange={(next) => { if (!next) onClose(); }} open={open}><SheetContent className="sm:max-w-lg"><SheetHeader><SheetTitle>{copy(language, "添加应用目录", "Add app catalog")}</SheetTitle><SheetDescription>{copy(language, "目录必须使用固定公钥签名。认证与自定义 CA 会加密保存。", "The catalog must be signed by the pinned public key. Authentication and custom CAs are encrypted at rest.")}</SheetDescription></SheetHeader><form className="flex min-h-0 flex-1 flex-col" onSubmit={(event) => void submit(event)}><div className="flex-1 overflow-y-auto px-4"><FieldGroup><Field><FieldLabel htmlFor="source-id">ID</FieldLabel><Input id="source-id" onChange={(event) => setSource((current) => ({ ...current, id: event.target.value }))} pattern="[a-z0-9-]+" required value={source.id} /></Field><Field><FieldLabel htmlFor="source-name">{copy(language, "显示名称", "Display name")}</FieldLabel><Input id="source-name" onChange={(event) => setSource((current) => ({ ...current, displayName: event.target.value }))} required value={source.displayName} /></Field><Field><FieldLabel htmlFor="source-url">URL</FieldLabel><Input id="source-url" onChange={(event) => setSource((current) => ({ ...current, url: event.target.value }))} required type="url" value={source.url} /></Field><Field><FieldLabel htmlFor="source-key">{copy(language, "Ed25519 公钥", "Ed25519 public key")}</FieldLabel><Textarea id="source-key" onChange={(event) => setSource((current) => ({ ...current, publicKey: event.target.value }))} required value={source.publicKey} /></Field><Field><FieldLabel htmlFor="source-token">Bearer Token</FieldLabel><Input id="source-token" onChange={(event) => setSource((current) => ({ ...current, bearerToken: event.target.value }))} type="password" value={source.bearerToken} /><FieldDescription>{copy(language, "公开目录可留空。", "Leave empty for a public catalog.")}</FieldDescription></Field><Field><FieldLabel htmlFor="source-ca">{copy(language, "自定义 CA（可选）", "Custom CA (optional)")}</FieldLabel><Textarea id="source-ca" onChange={(event) => setSource((current) => ({ ...current, customCA: event.target.value }))} value={source.customCA} /></Field>{error ? <FieldError>{error}</FieldError> : null}</FieldGroup></div><SheetFooter><Button onClick={onClose} type="button" variant="outline">{copy(language, "取消", "Cancel")}</Button><Button disabled={busy} type="submit">{busy ? <Spinner data-icon="inline-start" /> : null}{copy(language, "添加目录", "Add catalog")}</Button></SheetFooter></form></SheetContent></Sheet>;
}
