#!/bin/sh
set -eu

default_release_url="https://github.com/petauron/vastora/releases/latest/download/vastora-center-install.tar.gz"
release_url="$default_release_url"
install_dir="/opt/vastora/center"

usage() {
  cat <<'EOF'
Usage: install.sh center [--release-url HTTPS_URL] [--install-dir DIR] [-- SETUP_OPTIONS]

Installs the verified Vastora Center release bundle, then starts its guided
Center and Headscale setup. Agent installation commands are generated by Center.

Examples:
  curl -LsSf https://github.com/petauron/vastora/releases/latest/download/install.sh | sudo sh -s -- center
  ./install.sh center -- --center-url https://center.example.com \
    --headscale-url https://headscale.example.com:8443 \
    --tls-cert /path/to/fullchain.pem --tls-key /path/to/private-key.pem --yes
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi
if [ "${1:-}" != "center" ]; then
  echo "Choose 'center'. Agents are installed with the one-time command generated by Center." >&2
  usage >&2
  exit 2
fi
shift

while [ "$#" -gt 0 ]; do
  case "$1" in
    --release-url) release_url="$2"; shift 2 ;;
    --install-dir) install_dir="$2"; shift 2 ;;
    --) shift; break ;;
    *) break ;;
  esac
done

if [ "$(uname -s)" != "Linux" ]; then
  echo "Vastora Center installation currently supports Linux hosts." >&2
  exit 1
fi
if [ "$(id -u)" -ne 0 ]; then
  echo "Run the Center installer with sudo." >&2
  exit 1
fi
case "$release_url" in
  https://*) ;;
  *) echo "The Center release URL must use HTTPS." >&2; exit 2 ;;
esac
case "$install_dir" in
  /*) ;;
  *) echo "The installation directory must be an absolute path." >&2; exit 2 ;;
esac
if [ -e "$install_dir" ]; then
  echo "Center installation already exists at $install_dir; no files were changed." >&2
  echo "Inspect it there before retrying setup or performing an upgrade." >&2
  exit 1
fi

for required in curl tar mktemp install awk dirname mv; do
  if ! command -v "$required" >/dev/null 2>&1; then
    echo "Required command is not installed: $required" >&2
    exit 1
  fi
done
if command -v sha256sum >/dev/null 2>&1; then
  digest_command="sha256sum"
elif command -v shasum >/dev/null 2>&1; then
  digest_command="shasum -a 256"
else
  echo "Install sha256sum or shasum, then run the same command again." >&2
  exit 1
fi

temporary_dir="$(mktemp -d "${TMPDIR:-/tmp}/vastora-center-install.XXXXXX")"
archive="$temporary_dir/vastora-center-install.tar.gz"
checksum="$temporary_dir/vastora-center-install.tar.gz.sha256"
staging=""
cleanup() {
  rm -rf "$temporary_dir"
  if [ -n "$staging" ] && [ -d "$staging" ]; then
    rm -rf "$staging"
  fi
}
trap cleanup EXIT HUP INT TERM

echo "Downloading the Vastora Center release bundle..."
if ! curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release_url" -o "$archive"; then
  echo "No installable Center release was found. Check the release URL and try again." >&2
  exit 1
fi
if ! curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release_url.sha256" -o "$checksum"; then
  echo "The release checksum could not be downloaded; nothing was installed." >&2
  exit 1
fi

expected_digest="$(awk 'NR == 1 {print tolower($1)}' "$checksum")"
actual_digest="$($digest_command "$archive" | awk 'NR == 1 {print tolower($1)}')"
if [ -z "$expected_digest" ] || [ "$expected_digest" != "$actual_digest" ]; then
  echo "The Center release failed its SHA-256 integrity check; nothing was installed." >&2
  exit 1
fi

if ! tar -tzf "$archive" | while IFS= read -r entry; do
  case "$entry" in
    /*|..|./..|../*|*/../*|*/..) echo "Unsafe archive entry: $entry" >&2; exit 1 ;;
  esac
done; then
  echo "The Center release archive is unsafe; nothing was installed." >&2
  exit 1
fi
if ! tar -tvzf "$archive" | awk '$1 !~ /^[-d]/ {exit 1}'; then
  echo "The Center release archive contains unsupported links or special files." >&2
  exit 1
fi

install -d -m 0755 "$(dirname "$install_dir")"
staging="$(mktemp -d "${install_dir}.new.XXXXXX")"
tar -xzf "$archive" -C "$staging"
for required_file in setup.sh compose.yaml release.env headscale/config.yaml headscale/policy.hujson; do
  if [ ! -f "$staging/$required_file" ]; then
    echo "The Center release is incomplete: missing $required_file" >&2
    exit 1
  fi
done
chmod 0755 "$staging/setup.sh"
mv "$staging" "$install_dir"
staging=""

echo "Verified Center files installed at $install_dir"
rm -rf "$temporary_dir"
trap - EXIT HUP INT TERM
cd "$install_dir"
exec "$install_dir/setup.sh" "$@"
