export const dockerInstallDocsURLs = {
  debian: "https://docs.docker.com/engine/install/debian/",
  ubuntu: "https://docs.docker.com/engine/install/ubuntu/",
};

// A subshell keeps an unsupported host or an installation error from exiting
// the interactive terminal where the administrator pastes this command.
export const dockerInstallCommand = [
  "(",
  "set -eu",
  "",
  "if [ ! -r /etc/os-release ]; then",
  '  echo "Cannot identify this server: /etc/os-release is missing." >&2',
  "  exit 1",
  "fi",
  ". /etc/os-release",
  'case "${ID:-}:${VERSION_ID:-}" in',
  "  debian:12) distro=debian; codename=bookworm ;;",
  "  debian:13) distro=debian; codename=trixie ;;",
  "  ubuntu:22.04) distro=ubuntu; codename=jammy ;;",
  "  ubuntu:24.04) distro=ubuntu; codename=noble ;;",
  "  ubuntu:26.04) distro=ubuntu; codename=resolute ;;",
  "  *)",
  '    echo "Unsupported system: ${PRETTY_NAME:-unknown}. Use Debian 12/13 or Ubuntu 22.04/24.04/26.04." >&2',
  "    exit 1 ;;",
  "esac",
  "",
  "for required in apt-get dpkg dpkg-query systemctl; do",
  '  if ! command -v "$required" >/dev/null 2>&1; then',
  '    echo "Required command is not installed: $required" >&2',
  "    exit 1",
  "  fi",
  "done",
  'arch="$(dpkg --print-architecture)"',
  'case "$arch" in',
  "  amd64|arm64) ;;",
  '  *) echo "Unsupported architecture: $arch. Vastora requires amd64 or arm64." >&2; exit 1 ;;',
  "esac",
  "",
  "if command -v docker >/dev/null 2>&1; then",
  '  echo "Docker is already installed. Nothing was changed; start the daemon manually if needed."',
  "  exit 0",
  "fi",
  "for package in docker.io docker-compose docker-compose-v2 docker-doc docker-buildx podman-docker containerd runc; do",
  '  if [ "$(dpkg-query -W -f=\'${db:Status-Status}\' "$package" 2>/dev/null || true)" = "installed" ]; then',
  '    echo "Conflicting package: $package. Review the Docker documentation before replacing it; no packages were removed." >&2',
  "    exit 1",
  "  fi",
  "done",
  'if [ "$(id -u)" -ne 0 ] && ! command -v sudo >/dev/null 2>&1; then',
  '  echo "Run this command as root, or install sudo first." >&2',
  "  exit 1",
  "fi",
  "docker_install_as_root() {",
  '  if [ "$(id -u)" -eq 0 ]; then',
  '    "$@"',
  "  else",
  '    sudo "$@"',
  "  fi",
  "}",
  "",
  'echo "Installing Docker for $distro $VERSION_ID ($codename, $arch)..."',
  "docker_install_as_root apt-get update",
  "docker_install_as_root apt-get install --no-remove -y ca-certificates curl",
  "",
  "docker_install_as_root install -m 0755 -d /etc/apt/keyrings",
  'docker_install_as_root curl --proto \'=https\' --tlsv1.2 -fsS "https://download.docker.com/linux/$distro/gpg" \\',
  "  -o /etc/apt/keyrings/docker.asc",
  "docker_install_as_root chmod 0644 /etc/apt/keyrings/docker.asc",
  "",
  "docker_install_as_root tee /etc/apt/sources.list.d/docker.sources >/dev/null <<EOF",
  "Types: deb",
  "URIs: https://download.docker.com/linux/$distro",
  "Suites: $codename",
  "Components: stable",
  "Architectures: $arch",
  "Signed-By: /etc/apt/keyrings/docker.asc",
  "EOF",
  "docker_install_as_root chmod 0644 /etc/apt/sources.list.d/docker.sources",
  "",
  "docker_install_as_root apt-get update",
  "docker_install_as_root apt-get install --no-remove -y \\",
  "  docker-ce \\",
  "  docker-ce-cli \\",
  "  containerd.io \\",
  "  docker-buildx-plugin \\",
  "  docker-compose-plugin",
  "",
  "docker_install_as_root systemctl enable --now docker",
  "docker_install_as_root docker version",
  "docker_install_as_root docker compose version",
  ")",
].join("\n");
