-- +goose Up
CREATE TABLE agent_enrollment_tokens_v7 (
    token_hash BLOB PRIMARY KEY,
    site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    center_url TEXT NOT NULL,
    roles_json BLOB NOT NULL,
    capabilities_json BLOB NOT NULL,
    bootstrap_secret_id TEXT REFERENCES secrets(id) ON DELETE SET NULL,
    expires_at TEXT NOT NULL,
    used_at TEXT
);

-- Enrollment credentials expire after ten minutes. A restart intentionally
-- invalidates any command generated by the previous release instead of
-- preserving a command whose node profile was not bound by Center.
DROP TABLE agent_enrollment_tokens;
ALTER TABLE agent_enrollment_tokens_v7 RENAME TO agent_enrollment_tokens;
PRAGMA user_version = 7;
