// @vitest-environment jsdom
import { act } from "react";
import { describe, expect, it, vi } from "vitest";
import { DeploymentSheet, type DeploymentEditor } from "./DeploymentSheets";
import { dashboard, render, rerender } from "../views.test-support";
import type { AppView } from "../../types";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

function fixture() {
  const data = dashboard();
  const app = { ...data.apps[0], key: "community/new-monitor", sourceId: "community", app: { ...data.apps[0].app, id: "new-monitor", version: "1.0.0", packageRevision: 1, runtime: { kind: "systemd", version: 1, requiredCapabilities: ["root", "host-path"] }, config: [] } };
  data.apps = [app];
  data.applications = [];
  const editor: DeploymentEditor = { app, operation: "install" };
  return { data, app, editor };
}

const submitButton = () => document.querySelector<HTMLButtonElement>('[role="dialog"] button[type="submit"]');
const approval = (name: string) => document.getElementById(`package-capability-${name}`) as HTMLInputElement | null;

describe("declarative package deployment review", () => {
  it("does not render or submit Center-managed product fields, including defaults and required secrets", async () => {
    const { data, app } = fixture();
    const managed: AppView = { ...app, managedConfigFields: ["management_key", "cpa_base_url"], app: { ...app.app, runtime: { ...app.app.runtime, requiredCapabilities: [] }, config: [
      { key: "management_key", type: "string", required: true, secret: true, label: { en: "Managed credential", "zh-CN": "受管凭据" }, description: { en: "Generated by Center", "zh-CN": "主机生成" } },
      { key: "cpa_base_url", type: "string", required: true, secret: false, default: "https://managed.example.test", label: { en: "Managed service URL", "zh-CN": "受管服务地址" }, description: { en: "Resolved by Center", "zh-CN": "主机解析" } },
      { key: "label", type: "string", required: false, secret: false, default: "My node", label: { en: "Instance label", "zh-CN": "实例名称" }, description: { en: "Administrator choice", "zh-CN": "管理员输入" } },
    ] } };
    data.apps = [managed];
    const onSubmit = vi.fn(async () => undefined);
    render(<DeploymentSheet data={data} editor={{ app: managed, operation: "install" }} language="en" onClose={vi.fn()} onSubmit={onSubmit} />);
    expect(document.body.textContent).not.toContain("Managed credential");
    expect(document.body.textContent).not.toContain("Managed service URL");
    expect(document.body.textContent).toContain("Instance label");
    expect(submitButton()?.disabled).toBe(false);
    await act(async () => submitButton()?.click());
    expect(onSubmit).toHaveBeenCalledWith(data.agents[0], managed, { label: "My node" }, "install", undefined, "", []);
  });

  it("never preapproves privileges and submits only the explicitly approved capabilities", async () => {
    const { data, app, editor } = fixture();
    const onSubmit = vi.fn(async () => undefined);
    render(<DeploymentSheet data={data} editor={editor} language="en" onClose={vi.fn()} onSubmit={onSubmit} />);
    expect(approval("root")?.checked).toBe(false);
    expect(approval("host-path")?.checked).toBe(false);
    expect(submitButton()?.disabled).toBe(true);
    await act(async () => document.querySelector('[role="dialog"] form')?.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })));
    expect(onSubmit).not.toHaveBeenCalled();
    act(() => approval("root")?.click());
    expect(submitButton()?.disabled).toBe(true);
    act(() => approval("host-path")?.click());
    expect(submitButton()?.disabled).toBe(false);
    await act(async () => submitButton()?.click());
    expect(onSubmit).toHaveBeenCalledWith(data.agents[0], app, {}, "install", undefined, "", ["root", "host-path"]);
  });

  it("invalidates an open approval when the same upstream version gets a different package revision", async () => {
    const { data, app, editor } = fixture();
    const onSubmit = vi.fn(async () => undefined);
    const onClose = vi.fn();
    render(<DeploymentSheet data={data} editor={editor} language="en" onClose={onClose} onSubmit={onSubmit} />);
    act(() => { approval("root")?.click(); approval("host-path")?.click(); });
    expect(submitButton()?.disabled).toBe(false);
    const changed = { ...app, app: { ...app.app, packageRevision: 2 } };
    rerender(<DeploymentSheet data={{ ...data, apps: [changed] }} editor={editor} language="en" onClose={onClose} onSubmit={onSubmit} />);
    expect(submitButton()?.disabled).toBe(true);
    expect(document.getElementById("deployment-catalog-error")?.textContent).toContain("catalog version changed");
    await act(async () => document.querySelector('[role="dialog"] form')?.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })));
    expect(onSubmit).not.toHaveBeenCalled();
    // Reopening the new recipe must not carry forward the old authorization.
    rerender(<DeploymentSheet data={{ ...data, apps: [changed] }} editor={{ app: changed, operation: "install" }} language="en" onClose={onClose} onSubmit={onSubmit} />);
    expect(approval("root")?.checked).toBe(false);
    expect(submitButton()?.disabled).toBe(true);
  });

  it("blocks unsupported capabilities on an existing node and never sends a deployment", async () => {
    const { data, app } = fixture();
    app.app.runtime.requiredCapabilities = ["future-device"];
    const onSubmit = vi.fn(async () => undefined);
    render(<DeploymentSheet data={data} editor={{ app, agent: data.agents[0], operation: "upgrade" }} language="en" onClose={vi.fn()} onSubmit={onSubmit} />);
    expect(document.body.textContent).toContain("Missing node capabilities: future-device");
    act(() => approval("future-device")?.click());
    expect(submitButton()?.disabled).toBe(true);
    await act(async () => document.querySelector('[role="dialog"] form')?.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })));
    expect(onSubmit).not.toHaveBeenCalled();
  });

  it("invalidates approvals if the manifest digest changes even when the version and revision are unchanged", async () => {
    const { data, app, editor } = fixture();
    const onSubmit = vi.fn(async () => undefined);
    const onClose = vi.fn();
    render(<DeploymentSheet data={data} editor={editor} language="en" onClose={onClose} onSubmit={onSubmit} />);
    act(() => { approval("root")?.click(); approval("host-path")?.click(); });
    expect(submitButton()?.disabled).toBe(false);
    const changed = { ...app, manifestSha256: "b".repeat(64) };
    rerender(<DeploymentSheet data={{ ...data, apps: [changed] }} editor={editor} language="en" onClose={onClose} onSubmit={onSubmit} />);
    expect(submitButton()?.disabled).toBe(true);
    expect(document.getElementById("deployment-catalog-error")?.textContent).toContain("catalog version changed");
    await act(async () => document.querySelector('[role="dialog"] form')?.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })));
    expect(onSubmit).not.toHaveBeenCalled();
  });

  it("blocks mutation of pending-adoption resources without attempting reinstall", async () => {
    const { data, app } = fixture();
    app.app.runtime.requiredCapabilities = [];
    data.applications = [{ ...dashboard().applications[0], appKey: app.key, nodeId: data.agents[0].id, adoptionState: "pending", installedPackageRevision: 0 }];
    const onSubmit = vi.fn(async () => undefined);
    render(<DeploymentSheet data={data} editor={{ app, agent: data.agents[0], operation: "upgrade" }} language="en" onClose={vi.fn()} onSubmit={onSubmit} />);
    expect(document.body.textContent).toContain("Adoption does not reinstall or restart");
    expect(document.body.textContent).toContain("Recipe revision: 0 → 1");
    expect(submitButton()?.disabled).toBe(true);
    await act(async () => document.querySelector('[role="dialog"] form')?.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })));
    expect(onSubmit).not.toHaveBeenCalled();
  });
});
